name: hospitals
description: A sample command-line application.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  grpc: ^3.0.0
  protobuf: ^2.0.0
  csv: ^5.0.0
  dartz:
  dart_jts:
  basic_utils: ^5.2.0
  dart_jsonwebtoken: ^2.4.2
  logging: ^1.0.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  riverpod: ^0.14.0